### PR TITLE
Upgrade Conduit Dependency

### LINKED ISSUE #99: gogol-core build fails with latest conduit, servant
I saw these build failures on the Stackage build server, and was able to reproduce them locally like so:

```bash
stack unpack gogol-core-0.3.0 && cd gogol-core-0.3.0
edit stack.yaml # add the stack.yaml below
stack build
```

```yaml
resolver: nightly-2018-03-10
extra-deps:
- conduit-1.3.0
- resourcet-1.2.0
- servant-0.13
- http-types-0.12.1
```

The errors were as follows. Some caused by the new conduit, some by the new servant.

```
[5 of 6] Compiling Network.Google.Types ( src/Network/Google/Types.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/Network/Google/Types.o )

/Users/dan/scratch/gogol-core-0.3.0/src/Network/Google/Types.hs:179:15: error:
    Not in scope: type constructor or class ‘ResumableSource’
    |
179 | type Stream = ResumableSource (ResourceT IO) ByteString
    |               ^^^^^^^^^^^^^^^

/Users/dan/scratch/gogol-core-0.3.0/src/Network/Google/Types.hs:341:25: error:
    Ambiguous occurrence ‘Stream’
    It could refer to either ‘Servant.API.Stream’,
                             imported from ‘Servant.API’ at src/Network/Google/Types.hs:56:1-28
                             (and originally defined in ‘Servant.API.Stream’)
                          or ‘Network.Google.Types.Stream’,
                             defined at src/Network/Google/Types.hs:179:1
    |
341 |     , _cliResponse :: !(Stream -> ResourceT IO (Either (String, LBS.ByteString) a))
    |                         ^^^^^^

/Users/dan/scratch/gogol-core-0.3.0/src/Network/Google/Types.hs:363:12: error:
    Ambiguous occurrence ‘Stream’
    It could refer to either ‘Servant.API.Stream’,
                             imported from ‘Servant.API’ at src/Network/Google/Types.hs:56:1-28
                             (and originally defined in ‘Servant.API.Stream’)
                          or ‘Network.Google.Types.Stream’,
                             defined at src/Network/Google/Types.hs:179:1
    |
363 | client :: (Stream -> ResourceT IO (Either (String, LBS.ByteString) a))
    |            ^^^^^^

/Users/dan/scratch/gogol-core-0.3.0/src/Network/Google/Types.hs:399:19: error:
    Ambiguous occurrence ‘Stream’
    It could refer to either ‘Servant.API.Stream’,
                             imported from ‘Servant.API’ at src/Network/Google/Types.hs:56:1-28
                             (and originally defined in ‘Servant.API.Stream’)
                          or ‘Network.Google.Types.Stream’,
                             defined at src/Network/Google/Types.hs:179:1
    |
399 |                -> Stream
    |                   ^^^^^^

/Users/dan/scratch/gogol-core-0.3.0/src/Network/Google/Types.hs:402:33: error:
    Ambiguous occurrence ‘Stream’
    It could refer to either ‘Servant.API.Stream’,
                             imported from ‘Servant.API’ at src/Network/Google/Types.hs:56:1-28
                             (and originally defined in ‘Servant.API.Stream’)
                          or ‘Network.Google.Types.Stream’,
                             defined at src/Network/Google/Types.hs:179:1
    |
402 | instance FromStream OctetStream Stream where
    |                                 ^^^^^^

/Users/dan/scratch/gogol-core-0.3.0/src/Network/Google/Types.hs:602:12: error:
    Ambiguous occurrence ‘Stream’
    It could refer to either ‘Servant.API.Stream’,
                             imported from ‘Servant.API’ at src/Network/Google/Types.hs:56:1-28
                             (and originally defined in ‘Servant.API.Stream’)
                          or ‘Network.Google.Types.Stream’,
                             defined at src/Network/Google/Types.hs:179:1
    |
602 | sinkLBS :: Stream -> ResourceT IO LBS.ByteString
    |            ^^^^^^
```

### PR DESCRIPTION
**Pull request by brendanhay**
Closes #95, Fixes #99

### CODE REVIEW

**Comment by kk-hainq** [comment]
This looks nice and extremely helpful, @brendanhay!
Do you know when will this be able to get merged and released?
If there are still problems to address, can I offer some help?

**Comment by donatello** [comment]
Ping  @brendanhay - please merge and release this!

**Comment by saurabhnanda** [comment]
@brendanhay another gentle push from me 😄

**Comment by hasufell** [comment]
Quite useful, I'm also waiting for this :+1:

**Comment by rkrzr** [comment]
I'd also be interested in getting this one merged. Any chance for a new release?

**Comment by ChShersh** [comment]
I also would like to see that change released 🙂

**Comment by scottcmarks** [comment]
I would much rather use fully merged and checked out gogol-* than try to work around.  Any ideas about the check failures?

**Pull request merged**
